---
title: "ANES_2016_cleaning"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(haven)
library(tidyverse)
library(labelled)
```


```{r}

anes_2016_orig<-read_dta("anes_timeseries_2016.dta")


dim(anes_2016_orig)
```



```{r}

anes_new_2016 = anes_2016_orig[,FALSE]

```

```{r}
#ID
anes_new_2016$ID = anes_2016_orig$V160001

anes_new_2016$weights <- anes_2016_orig$V160102


```





```{r}
#Spending

anes_new_2016$ss = anes_2016_orig$V161205
anes_new_2016$healthcare = anes_2016_orig$V162193
anes_new_2016$school = anes_2016_orig$V161206
anes_new_2016$welfare = anes_2016_orig$V161209
anes_new_2016$env = anes_2016_orig$V161212
anes_new_2016$poor = anes_2016_orig$V161211
anes_new_2016$sci = anes_2016_orig$V161207







```


```{r}
#Redistribution

anes_new_2016$tax_mill = anes_2016_orig$V162140
anes_new_2016$red_ineq = anes_2016_orig$V162276
anes_new_2016$min_wage = anes_2016_orig$V162192
anes_new_2016$job_gov = anes_2016_orig$V161189


```








```{r}
#demographic


anes_new_2016$sex_orig <- anes_2016_orig$V161342
anes_new_2016$sex <- NA

anes_new_2016$sex[anes_new_2016$sex_orig ==1] =1
anes_new_2016$sex[anes_new_2016$sex_orig ==2] =0

anes_new_2016$white <- anes_2016_orig$V161310a
anes_new_2016$black <- anes_2016_orig$V161310b
anes_new_2016$asian <- anes_2016_orig$V161310d
anes_new_2016$hisp <- anes_2016_orig$V161309




anes_new_2016 <- anes_new_2016 %>% dplyr::mutate(
  hisp= case_when(
    hisp==1~ 1,
    hisp==2~ 0))  





anes_new_2016$born <- anes_2016_orig$V161316
anes_new_2016$class <- anes_2016_orig$V161305a
anes_new_2016$educ <- anes_2016_orig$V161270
anes_new_2016$income <- anes_2016_orig$V161361x
anes_new_2016$age <- anes_2016_orig$V161267



anes_new_2016$educ[anes_new_2016$educ == 95] <- NA


anes_new_2016 <- anes_new_2016 %>% dplyr::mutate(
  class= case_when(
    class==0~ 0,
    class==2~ 1,
    class==1~ 2, 
   class==3~ 2,
   class==4~ 3,))  


```



```{r}
#race q's

anes_new_2016$black_favors <- anes_2016_orig$V162211
anes_new_2016$blm <- anes_2016_orig$V162113
anes_new_2016$black_deserve <- anes_2016_orig$V162213
anes_new_2016$black_try <- anes_2016_orig$V162214
anes_new_2016$slave <- anes_2016_orig$V162212


anes_new_2016 <- anes_new_2016 %>% dplyr::mutate(
  black_try= case_when(
    black_try==1~ 5,
    black_try==2~ 4,
    black_try==3 ~3,
   black_try==4 ~2,
   black_try==5 ~1))  


anes_new_2016 <- anes_new_2016 %>% dplyr::mutate(
  black_favors= case_when(
    black_favors==1~ 5,
    black_favors==2~ 4,
    black_favors==3 ~3,
   black_favors==4 ~2,
   black_favors==5 ~1))  


anes_new_2016 <- anes_new_2016 %>% dplyr::mutate(
  slave= case_when(
    slave==1~ 5,
    slave==2~ 4,
    slave==3 ~3,
   slave==4 ~2,
   slave==5 ~1))  








```

```{r}
#politics
anes_new_2016$vote_duty <- anes_2016_orig$V161151x


anes_new_2016 <- anes_new_2016 %>% dplyr::mutate(
  vote_duty= case_when(
    vote_duty==1~ 3,
    vote_duty==2~ 1,
    vote_duty==3 ~2))  



anes_new_2016$int_camp <- anes_2016_orig$V161004

anes_new_2016$int_pol <- anes_2016_orig$V162256



anes_new_2016$int_med <- anes_2016_orig$V162257


anes_new_2016$lib_con_spec <- anes_2016_orig$V161126


```





```{r}
#party id
anes_new_2016$party_id <- anes_2016_orig$V161155
anes_new_2016$strong_weak <- anes_2016_orig$V161156
anes_new_2016$ind <- anes_2016_orig$V161157
anes_new_2016$seven_point <- NA
anes_new_2016$seven_point[anes_new_2016$party_id == 1 & anes_new_2016$strong_weak == 1 ] <- 1
anes_new_2016$seven_point[anes_new_2016$party_id == 1 & anes_new_2016$strong_weak == 2 ] <- 2
anes_new_2016$seven_point[anes_new_2016$party_id == 3 & anes_new_2016$ind == 3] <- 3
anes_new_2016$seven_point[anes_new_2016$party_id == 3 & anes_new_2016$ind == 2] <- 4
anes_new_2016$seven_point[anes_new_2016$party_id == 3 & anes_new_2016$ind == 1] <- 5
anes_new_2016$seven_point[anes_new_2016$party_id == 2 & anes_new_2016$strong_weak == 2] <- 6
anes_new_2016$seven_point[anes_new_2016$party_id == 2 & anes_new_2016$strong_weak == 1] <- 7


```


```{r}

#lib norms
anes_new_2016$trad <- anes_2016_orig$V162169
anes_new_2016$true <- anes_2016_orig$V162170
anes_new_2016$bend <- anes_2016_orig$V162263


```






```{r}

#rescale some variables
anes_new_2016 <- anes_new_2016 %>% dplyr::mutate(
  int_camp= case_when(
    int_camp==1~ 3,
    int_camp==2~ 2,
    int_camp==3 ~1))  


anes_new_2016 <- anes_new_2016 %>% dplyr::mutate(
  int_pol= case_when(
    int_pol==1~ 4,
    int_pol==2~ 3,
    int_pol==3 ~2,
    int_pol==4 ~1,))  



anes_new_2016 <- anes_new_2016 %>% dplyr::mutate(
  int_med= case_when(
    int_med==1~ 4,
    int_med==2~ 3,
    int_med==3 ~2,
    int_med==4 ~1,))  






anes_new_2016 <- anes_new_2016 %>% dplyr::mutate(
  tax_mill= case_when(
    tax_mill==1~ 3,
    tax_mill==2~ 1,
    tax_mill==3 ~2))  


anes_new_2016 <- anes_new_2016 %>% dplyr::mutate(
  red_ineq= case_when(
    red_ineq==1~ 3,
    red_ineq==2~ 1,
    red_ineq==3 ~2))  


anes_new_2016 <- anes_new_2016 %>% dplyr::mutate(
  min_wage= case_when(
    min_wage==1~ 4,
    min_wage==2~ 3,
    min_wage==3 ~2,
    min_wage==4 ~1,))  



anes_new_2016 <- anes_new_2016 %>% dplyr::mutate(
  job_gov= case_when(
    job_gov==7~ 1,
    job_gov==6~ 2,
    job_gov==5 ~3,
    job_gov==4 ~4,
    job_gov==3 ~5,
    job_gov==2 ~6,
    job_gov==1 ~7))  



anes_new_2016 <- anes_new_2016 %>% dplyr::mutate(
  welfare= case_when(
    welfare==1~ 3,
    welfare==2~ 1,
    welfare==3 ~2))  



anes_new_2016 <- anes_new_2016 %>% dplyr::mutate(
  healthcare= case_when(
    healthcare==1~ 3,
    healthcare==2~ 1,
    healthcare==3 ~2))  



anes_new_2016 <- anes_new_2016 %>% dplyr::mutate(
  school= case_when(
    school==1~ 3,
    school==2~ 1,
    school==3 ~2))  




anes_new_2016 <- anes_new_2016 %>% dplyr::mutate(
  ss= case_when(
    ss==1~ 3,
    ss==2~ 1,
    ss==3 ~2))  




anes_new_2016 <- anes_new_2016 %>% dplyr::mutate(
  env= case_when(
    env==1~ 3,
    env==2~ 1,
    env==3 ~2))  





anes_new_2016 <- anes_new_2016 %>% dplyr::mutate(
  poor= case_when(
    poor==1~ 3,
    poor==2~ 1,
    poor==3 ~2))  


```





```{r}
#remove NAs, save data
anes_new_2016$ID <- as.character(anes_new_2016$ID )
anes_new_2016_cln <- anes_new_2016
anes_new_2016_cln[anes_new_2016_cln < 0 | anes_new_2016_cln >= 99] <- NA

anes_num = anes_new_2016_cln
anes_num <- remove_labels(anes_num)
unique(anes_num$lib_con_spec)
write.csv(anes_num, "anes_num_pca_16.csv")



```

