---
title: "pca_psych-2016"
output:
  pdf_document: default
  html_document: default
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(ggplot2)
library(tidyverse)
library(factoextra)
library(Amelia)
library(psych)
library(stargazer)
library(rlist)



```

```{r}

anes_num_pca_16 <- read_csv('anes_num_pca_16.csv')


anes_num_pca_16 <- data.frame(anes_num_pca_16)



```



```{r}

#create lib dem pca
lib_pca_data <-anes_num_pca_16 %>% dplyr::select(trad, true, bend)

lib_pca1 <- principal(lib_pca_data[,-1], nfactors=1, score=TRUE, missing = T, impute = "mean")

lib_pca1


anes_num_pca_16$lib_pca1<- lib_pca1$scores[,1]
```


```{r}
#create political interest pca
pol_pca_data <-anes_num_pca_16 %>% dplyr::select(vote_duty,int_pol, int_med)

pol_pca1 <- principal(pol_pca_data[,-1], nfactors=1, score=TRUE, missing = T, impute = "mean")

pol_pca1
anes_num_pca_16$pol_pca1<- pol_pca1$scores[,1]


```

```{r}
#create redistribution pca
redist_pca_data <-anes_num_pca_16 %>% dplyr::select(tax_mill, job_gov, min_wage)

redist_pca1 <- principal(redist_pca_data[,-1], nfactors=1, score=TRUE, missing = T, impute = "mean")

redist_pca1
anes_num_pca_16$redist_pca1<- redist_pca1$scores



```

```{r}
#create spending pca
spend_pca_data <-anes_num_pca_16 %>% dplyr::select(school, poor, welfare, healthcare)

spend_pca1 <- principal(spend_pca_data[,-1], nfactors=1, score=TRUE, missing = T, impute = "mean")
spend_pca1

anes_num_pca_16$spend_pca1<- spend_pca1$scores

```


```{r}
#rescale variables
anes_num_pca_16$lib_pca1_scaled <- scale(anes_num_pca_16$lib_pca1)
anes_num_pca_16$redist_pca1_scaled <- scale(anes_num_pca_16$redist_pca1)
anes_num_pca_16$spend_pca1_scaled <- scale(anes_num_pca_16$spend_pca1)
anes_num_pca_16$pol_pca1_scaled <- scale(anes_num_pca_16$pol_pca1)


```




```{r}


unique(anes_num_pca_16$lib_con_spec)
write.csv(anes_num_pca_16, "anes_num_pca_16_new.csv")

```

