---
title: "PCA_Psych"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(ggplot2)
library(tidyverse)
library(factoextra)
library(Amelia)
library(psych)
library(stargazer)

```


```{r}
setwd("~/Downloads/JP")
anes_num_pca <- read_csv('anes_num_pca.csv')




```


```{r}
#create lib dem pca
lib_pca_data <-anes_num_pca %>% dplyr::select(branches, consq, facts, crit)


lib_pca1 <- principal(lib_pca_data[,-1], nfactors=1, score=TRUE, missing = T, impute = "mean")

lib_pca1
anes_num_pca$lib_pca1<- lib_pca1$scores



cor.test(anes_num_pca$consq, anes_num_pca_16$bend, 
                    method = "pearson")


```







```{r}
#create political interest pca
pol_pca_data <-anes_num_pca %>% dplyr::select(vote_duty, int_pol, int_med)

pol_pca1 <- principal(pol_pca_data[,-1], nfactors = 1, score=TRUE,missing = T, impute = "mean")
pol_pca1

anes_num_pca$pol_pca1<- pol_pca1$scores


cor.test(anes_num_pca$int_pol, anes_num_pca$int_med, 
                    method = "pearson")

```


```{r}
#create redistribution pca
redist_pca_data <-anes_num_pca %>% dplyr::select(tax_mill, red_ineq, job_gov, min_wage)

redist_pca1 <- principal(redist_pca_data[,-1], nfactors=1, score=TRUE, missing = T, impute = "mean")
redist_pca1

anes_num_pca$redist_pca1<- redist_pca1$scores



cor.test(anes_num_pca$red_ineq, anes_num_pca$job_gov, 
                    method = "pearson")

```

```{r}
#create spending pca
spend_pca_data <-anes_num_pca %>% dplyr::select(healthcare, school, poor, welfare)

spend_pca1 <- principal(spend_pca_data[,-1], nfactors=1, score=TRUE, missing = T, impute = "mean")

spend_pca1
anes_num_pca$spend_pca1<- spend_pca1$scores


cor.test(anes_num_pca$school, anes_num_pca$healthcare, 
                    method = "pearson")

```



```{r}
#rescale variables
anes_num_pca$lib_pca1_scaled <- scale(anes_num_pca$lib_pca1)
anes_num_pca$redist_pca1_scaled <- scale(anes_num_pca$redist_pca1)
anes_num_pca$spend_pca1_scaled <- scale(anes_num_pca$spend_pca1)
anes_num_pca$rr_pca1_scaled <- scale(anes_num_pca$rr_pca1)
anes_num_pca$pol_pca1_scaled <- scale(anes_num_pca$pol_pca1)


write.csv(anes_num_pca, "anes_num_pca_new.csv")
```



